### ISSUE TITLE
Sobre carga del servidor en casos de catálogos largos.

### ISSUE THREAD

**Issue by vandark25** [PayTpv/PAYTPV-Magento#6]
Buenos días, hemos tenido que desactivar la opción de filtrar por producto ya que por defecto la extension intenta cargar todos los productos en memoria, y cuando se tienen mas de 100.000 sobre carga el servidor y da errores.

Lo he desactivado asi.

`<?php
class Mage_PayTpvCom_Model_System_Config_Source_Product
{
    public function toOptionArray($isMultiselect = false)
    /*public function toOptionArray($isMultiselect = false)
    {
		
        $options = Mage::getModel('catalog/product')->getCollection()
        }

        return $items;
    }*/

    /* Ontic: Parcheamos el método para que no devuelva resultados y así desactivar esta funcionalidad */
    public function toOptionArray($isMultiselect = false)
    {
        $options = Mage::getModel('catalog/product')->getCollection()
            ->addAttributeToFilter('status', 1)
            ->addAttributeToFilter('entity_id', -1)
            ->addAttributeToSort('name', 'ASC');
        
        foreach ($options as $product) {
            $items[] = array("value"=>$product->getId(), "label"=>$product->getName() . " (" . $product->getSku() . ")");
        }

        return $items;
    }
}
`

**Comment by txerragh** [comment]
Por favor, cualquier duda abra ticket a través del área de cliente de PAYTPV.
