### ISSUE TITLE
Solicutud de nueva funcion

### ISSUE THREAD

**Issue by vandark25** [PayTpv/PAYTPV-Magento#7]
Seria posible añadir un Tooltip o mensaje de texto debajo del método de pago, para poder explicar a los clientes como meter el numero de tarjeta?

Ejemplo
imagen
https://imgur.com/a/OgQ9kSc

**Comment by txerragh** [comment]
Por favor, cualquier duda abra ticket a través del área de cliente de PAYTPV.
